name: ridebuddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^8.1.4
  change_app_package_name: ^1.4.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/net.png
    - assets/circleEarth.png
    - assets/brandCar.png
    - assets/kyc.png
    - assets/fastDel.png
    - assets/fastTag.png
    - assets/gps.png
    - assets/package.png
